03.10. 22:22:02 Time difference: 00:00:00:00
make trotter
Qubits set to  {1, 2, 3, 4}
Arguments where set as:
	sum: False
	pntsamples: 16
	pntsinglesamples: 100
	persamples: 100
	shots: 1024
	backend: FakeVigoV2
	cross: False
	onlyTomography: False
	setqubits: {1, 2, 3, 4}
	depths: [2, 4, 8, 16]
Namebase will be: False_16_100_100_1024_FakeVigoV2_False_False_{1, 2, 3, 4}_[2, 4, 8, 16]
initialize experiment
03.10. 22:22:02 Time difference: 00:00:00:00
generate circuits
03.10. 22:22:02 Time difference: 00:00:00:00
run experiment
03.10. 22:22:26 Time difference: 00:00:00:23
analyse experiment
03.10. 22:22:39 Time difference: 00:00:00:12
Saving data
03.10. 22:22:51 Time difference: 00:00:00:12
Traceback (most recent call last):
  File "/localdisk/fabrice_remote_experiments/AutomatedPERTools/tutorial_notebooks/testrun/TrotterExample.py", line 587, in <module>
    main()
  File "/localdisk/fabrice_remote_experiments/AutomatedPERTools/tutorial_notebooks/testrun/TrotterExample.py", line 453, in main
    for layer in experiment.analysis.get_all_layer_data():
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Analysis' object has no attribute 'get_all_layer_data'. Did you mean: 'get_layer_data'?
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/localdisk/fabrice_remote_experiments/AutomatedPERTools/tutorial_notebooks/testrun/TrotterExample.py", line 185, in make_transfer_matrix
    with open("server_run_collection/" + namebase + "transfer_matrixes.pickle", "wb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'server_run_collection/False_16_100_100_1024_FakeVigoV2_False_False_{1, 2, 3, 4}_[2, 4, 8, 16]/transfer_matrixes.pickle'
